import './globals.css'
import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { Dialog, DialogContent, DialogHeader } from '@/components/ui/dialog'
// to change font
import { Open_Sans } from 'next/font/google'
const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Team chat Application',
  description: 'Generated by create next app',

}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <>
      <meta
        name="format-detection"
        content="telephone=no, date=no, email=no, address=no"
      />
      <ClerkProvider>
        <html lang="en">
          <body className={`${font.className} dark:bg-[#313338] w-full h-screen`}>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              storageKey="discord-theme"
            >
              {children}
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </>
  )
}


